apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: nextjs
  ports:
  - port: 80
    targetPort: 3000